msrv = "1.70.0"
cognitive-complexity-threshold = 30
too-many-lines-threshold = 100
type-complexity-threshold = 60
trivial-copy-size-limit = 64
avoid-breaking-exported-api = false
check-private-items = false 